### ISSUE TITLE
Complex ICA weights while using eeg_checkset

### ISSUE THREAD

**Issue by piyushswami04** [goodshawn12/orica#1] opened 2021-09-14 17:23 UTC
Hi,
Related to complex and non-complex outputs:
1) While running the provided testScript.m and dataset (SIM_STAT_16ch_3min.set):
When EEG = eeg_checkset(EEG); is uncommented (as it is in the code), the result is complex values of ICA weights. Whereas, if I comment EEG = eeg_checkset(EEG);, the result is non-complex values. 
Is this an expected result?
Why EEG = eeg_checkset(EEG); results in complex ICA weights?
2) While running the provided testScript.m with my own EEG data (which is .edf format) collected in the lab:
Comment/uncomment EEG = eeg_checkset(EEG); produces the same non-complex values.
Is this an expected result?

Related to plot:
3) Unable to plot and result in the following error message. Can you please check the last line of testScript.m?
Error using surface
Complex values are not supported.

Error in topoplot (line 1169)
       tmph = surface(Xi-delta/2,Yi-delta/2,zeros(size(Zi))-0.1,Zi,...

Error in pop_topoplot (line 370)
                 tmpobj = topoplot( EEG.icawinv(:, arg2(index)), EEG.chanlocs,
                 options{:} );

Error in testScript3 (line 50)
pop_topoplot(EEG,0,1:EEG.nbchan);

**Comment by goodshawn12** [comment] 2021-09-15 17:45
Hi,

Can you check if EEG.icawinv (inverse of ICA weights x sphereing matrix)
contained any complex values too? From your comment #3 it seems that it did.

The complex values could come from either the matrix inversion or
normalization performed in eeg_checkset. And the root cause is likely a
rank deficient data. Do you see the same problem for other datasets?

Best,
Shawn

**Comment by piyushswami88** [comment] 2021-09-17 08:58
Hi Shawn, 

I appreciate your prompt response. Yes, EEG.icawinv contains complex values.

OK. Yes, I see the same problem when I checked it with sample dataset - eeglab_data.set provided in eeglab. It seem this problem only occurs if the the dataset is in structure type.

1) When I comment only EEG = eeg_checkset(EEG); , the code works fine. Can you please let me know if it would be ok to use the code like this?
2) I also had a problem related to conversion of this code which has been fixed by using V = real(V); and D = real(D); in "% orthogonalize weight matrix" of orica.m. The resultant values of V and D discarded are still zero. Just to check, can you please let me know if this would be ok? 

If required, details about 2) are in this link: https://se.mathworks.com/matlabcentral/answers/1452169-error-in-generating-c-c-codes-cannot-assign-a-complex-value-into-a-non-complex-location?s_tid=prof_contriblnk

Thanking you! 🙂
Piyush

**Comment by piyushswami04** [comment] 2021-09-17 12:23
Hi Shawn, I appreciate your prompt response 🙂 

Yes, EEG.icawinv contains complex values.

OK. Yes, I see the same problem when I checked it with the sample dataset - eeglab_data.set. It seems this problem only occurs if the dataset is in structure type. When I comment only EEG = eeg_checkset(EEG);, the code works fine. Can you please let me know if it would be ok to use the code like this?

Thanking you!
Piyush

**Closed as completed** 2021-12-01 15:59 UTC
